### ISSUE TITLE
Unable to run standalone 0.1.2-snapshot on windows

### ISSUE THREAD

**Issue by mooreds** [ftomassetti/effectivejava#45]
So, downloaded the 01.2-SNAPSHOT.jar file.  Trying to run it on Windows 7 with java 8:

$ java -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)

Both from bash and from the cmd prompt, I get a null pointer exception:

```
C:\Users\dan.moore\project\effectivejava>java -jar effectivejava-0.1.2-SNAPSHOT-standalone.jar
Exception in thread "main" java.lang.ExceptionInInitializerError
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:344)
        at clojure.lang.RT.loadClassForName(RT.java:2093)
        at clojure.lang.RT.load(RT.java:430)
        at clojure.lang.RT.load(RT.java:411)
        at clojure.core$load$fn__5066.invoke(core.clj:5641)
        at clojure.core$load.doInvoke(core.clj:5640)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at app.core__init.load(Unknown Source)
        at app.core__init.<clinit>(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:344)
        at clojure.lang.RT.loadClassForName(RT.java:2093)
        at clojure.lang.RT.load(RT.java:430)
        at clojure.lang.RT.load(RT.java:411)
        at clojure.core$load$fn__5066.invoke(core.clj:5641)
        at clojure.core$load.doInvoke(core.clj:5640)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.lang.Var.invoke(Var.java:379)
        at app.core.<clinit>(Unknown Source)
Caused by: java.lang.NullPointerException
        at app.javaparser__init.load(Unknown Source)
        at app.javaparser__init.<clinit>(Unknown Source)
        ... 20 more
```

I get a similar error when running it in lint mode.

**Comment by ftomassetti** [comment]
Could you try instead to clone the project and run:
```
lein jar
java -jar effectivejava-0.1.3-SNAPSHOT-standalone.jar -l -d "<myJavaProjectDir>"
```

?

version 0.1.2 is a bit old, I do not remember if I built it as an uberjar (i.e., including all the dependencies, including JavaParser). Probably I should remove it from the repository. I would do that after publishing the next version to clojars and maven central

**Comment by davidor** [comment]
I get the same error in Linux when executing java -jar effectivejava-0.1.2-SNAPSHOT-standalone.jar

**Comment by ftomassetti** [comment]
ok, we are definitely going to remove that old version and provide uberjar separately (not in the repository)

**Comment by ftomassetti** [comment]
we removed the releases directory.
We will add releases file on GitHub and then close this issue.

**Comment by ftomassetti** [comment]
The old release (broken) was removed. The new one (0.1.3) is available at https://github.com/ftomassetti/effectivejava/releases please let me know if you are experiencing problem with it. Feel free to open a new issue in that case.

Thank you for reporting this error!
